services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: CLIENTE
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
